version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: catering_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: catering_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Opcional: Una interfaz web para ver la BD si no quieres instalar TablePlus
  pgadmin:
    image: dpage/pgadmin4
    container_name: catering_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data: